[package]
name = "ewar-bot"
version = "0.0.1"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
poise = "0.6.1"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
