CREATE TABLE IF NOT EXISTS players
(
    player_id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    player_name VARCHAR(32)      NOT NULL,
    rating      DOUBLE PRECISION NOT NULL DEFAULT 18,
    deviation   DOUBLE PRECISION NOT NULL DEFAULT 9,
    last_played TIMESTAMP WITHOUT TIME ZONE,
    UNIQUE (player_name)
);

CREATE TABLE IF NOT EXISTS player_discord
(
    player_id       INT    NOT NULL,
    discord_user_id BIGINT NOT NULL,
    FOREIGN KEY (player_id) REFERENCES players (player_id),
    UNIQUE (player_id, discord_user_id)
);

CREATE INDEX discord_user_id ON player_discord (discord_user_id);
