name: build it

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install dependencies
        run: sudo apt-get install -y mingw-w64

      - name: Build project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Linux build artifact
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: target/x86_64-unknown-linux-gnu/release/ewar-bot

      - name: Upload Windows build artifact
        if: matrix.target == 'x86_64-pc-windows-gnu'
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: target/x86_64-pc-windows-gnu/release/ewar-bot.exe
